@id=0b02de97-4c31-42b8-bd41-4b9e0229bcdd

PUT http://localhost:5204/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine - modified",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2023-05-23T08:00:00",
    "endDateTime": "2023-06-23T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}